version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    command: ["start"]
    restart: unless-stopped
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL_HOST=keycloak-database
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=12345678
      - KC_DB_POOL_MAX_SIZE=10
      - KC_HOSTNAME_STRICT=false
      - KC_HTTPS_CERTIFICATE_FILE=/opt/keycloak/conf/keycloak-server.cry.pem
      - KC_HTTPS_CERTIFICATE_KEY_FILE=/opt/keycloak/conf/keycloak-server.key.pem
    ports:
      - 8080:8080
      - 8443:8443
    depends_on:
      - keycloak-database
    networks:
      - keycloak-network
    volumes:
      - ./keycloak-server.cry.pem:/opt/keycloak/conf/keycloak-server.cry.pem
      - ./keycloak-server.key.pem:/opt/keycloak/conf/keycloak-server.key.pem
    security_opt:
      - seccomp:unconfined
  keycloak-database:
    image: "postgres"
    environment:
      - POSTGRES_PASSWORD=12345678
    ports:
      - 5555:5432
    volumes:
      - ./data:/var/lib/postgresql/data/
    networks:
      - keycloak-network
networks:
  keycloak-network: